amicpelut/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
import adoptions.sitemaps as adoptions_sitemaps
import organizations.sitemaps as organizations_sitemaps
from amicpelut import settings
from . import views


urlpatterns = (
    i18n_patterns(
        path("", include("core.urls")),
        path("", include("organizations.urls")),
        path("", include("adoptions.urls")),
        path("admin/", admin.site.urls),
        prefix_default_language=False,
    )
    + [
        path(
            "sitemap.xml",
            sitemap,
            {
                "sitemaps": {
                    "protectores": organizations_sitemaps.OrganizationSitemap,
                    "animals": adoptions_sitemaps.PetSitemap,
                }
            },
            name="sitemap",
        ),
        path("robots.txt", views.robots_txt, name="robots"),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)


handler404 = views.not_found_handler
handler500 = views.internal_error_handler


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("500", views.internal_error_handler, name="internal_error"),
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

core/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("sobre-nosaltres", views.about, name="about"),
    path("contacte", views.send_contact_email, name="send_contact_email"),
    path("panell", views.dashboard, name="dashboard"),
    path(
        "usuari/entrar", LoginView.as_view(template_name="core/users/login.html", success_url="dashboard"), name="login"
    ),
    path("usuari/sortir", views.logout_view, name="logout"),
]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name=_("Correu electrònic"))

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        ordering = ("id", "email")
        db_table = "auth_user"

core/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Invisible
from django import forms
from django.utils.translation import gettext_lazy as _


class SendContactEmailForm(forms.Form):
    name = forms.CharField(label=_("Nom i cognoms"), widget=forms.TextInput(attrs={"placeholder": _("El teu nom")}))
    email = forms.EmailField(
        label=_("Correu electrònic"), widget=forms.EmailInput(attrs={"placeholder": _("exemple@email.com")})
    )
    message = forms.CharField(widget=forms.Textarea(attrs={"placeholder": ""}), label=_("Missatge"))
    captcha = ReCaptchaField(widget=ReCaptchaV2Invisible, label="", required=True)

core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.translation import gettext_lazy as _

from adoptions import views as adoptions_views
from adoptions.models import Pet
from core.forms import SendContactEmailForm

PETS_PER_PAGE = 20


def home(request: HttpRequest) -> HttpResponse:
    return adoptions_views.home(request)


def about(request: HttpRequest) -> HttpResponse:
    form = SendContactEmailForm()
    return render(request, "core/about/about.html", {"section": "about", "contact_form": form})


def send_contact_email(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = SendContactEmailForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]
            subject = _("%(name)s (Formulari de contacte)" % {"name": form.cleaned_data["name"]})
            body = f"Missatge de {name} ({email}):\n\n{message}"
            msg = EmailMessage(
                from_email=f"{name} <contacte@amicpelut.com>",
                to=["contacte@amicpelut.com"],
                reply_to=[form.cleaned_data["email"]],
                subject=subject,
                body=body,
            )
            msg.send()
            messages.success(request, _("El missatge s'ha enviat correctament."))
        else:
            messages.error(request, _("No s'ha pogut enviar el missatge. Sisplau, torna a intentar-ho més tard."))
    return redirect(to="core:about")


@login_required()
def dashboard(request: HttpRequest) -> HttpResponse:
    organization = request.user.adoptions.organization
    cats = Pet.objects.filter(type=Pet.Type.CAT, organization=organization).order_by("adopted", "pk")
    dogs = Pet.objects.filter(type=Pet.Type.DOG, organization=organization).order_by("adopted", "pk")

    status_code = 200
    if request.method == "POST":
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, _("Contrasenya canviada amb èxit!"))
        else:
            messages.error(request, _("No s'ha pogut canviar la contrasenya"))
            status_code = 400
    else:
        password_form = PasswordChangeForm(request.user)

    return render(
        request,
        "core/dashboard.html",
        {"section": "dashboard", "organization": organization, "cats": cats, "dogs": dogs, "user_form": password_form},
        status=status_code,
    )


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    messages.success(request, _("S'ha tancat la sessió correctament."))
    return redirect(to="core:home")

core/templates/core/about/about.html
{% extends 'core/layout.html' %}

{% load i18n %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
  <h1>{% trans "Sobre nosaltres" %}</h1>

  <div class="row">
    <div class="col-12 col-md-6">
      {% spaceless %}
        {% blocktrans %}
          <p>
            Aquest és un projecte sense cap ànim de lucre amb l'objectiu d'ajudar als nostres amics peluts a trobar una
            família, tenir una vida digne i gaudir-la plenament com es mereixen.
          </p>

          <p>
            Creiem que l'adopció és la millor manera de trobar un animal de companyia. Un animal és un ésser viu que,
            com els humans, té dret a tenir una vida digna. Les protectores d'animals i cases d'acollida reben molts
            animals cada any que necessiten trobar una llar on poder ser feliços. Per altra banda, creiem que "comprar"
            animals en una botiga fa que es vegin com un producte o un objecte i no com el que són.
          </p>
        {% endblocktrans %}
      {% endspaceless %}
    </div>
    <div class="col-12 col-md-6">
      <p>
        <img src="{% static "images/gats.jpg" %}" alt="" class="w-100"/>
      </p>
    </div>
  </div>

  <h2 id="contacte">{% trans "Contacte" %}</h2>

  {% blocktrans %}
    <p>
      Si tens alguna pregunta, suggeriment o missatge que vulguis fer-nos arribar, pots fer-ho a
      <a href="mailto:contacte@amicpelut.com">contacte@amicpelut.com</a> o utilitzant el següent formulari:
    </p>
  {% endblocktrans %}

  <div class="mb-1">
    <form action="{% url "core:send_contact_email" %}" method="post" class="mx-auto" style="max-width: 600px">
      {% csrf_token %}
      {% bootstrap_form contact_form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
          <i class="fas fa-paper-plane mr-1"></i>
          {% trans "Enviar" %}
        </button>
      {% endbuttons %}
    </form>
  </div>
{% endblock %}