adoptions/urls.py
from django.urls import path

from adoptions import views

app_name = "adoptions"

urlpatterns = [
    path("gats", views.cats, name="cats"),
    path("gat/<int:pet_id>/<str:pet_slug>", views.cat_detail, name="cat_detail"),
    path("gossos", views.dogs, name="dogs"),
    path("gos/<int:pet_id>/<str:pet_slug>", views.dog_detail, name="dog_detail"),
    path("adoptats", views.AdoptedPets.as_view(), name="adopted"),
    path("adoptar/<int:pet_id>", views.adopt_pet, name="adopt_pet"),
    path("cancelar-adopcio/<int:pet_id>", views.cancel_pet_adoption, name="cancel_pet_adoption"),
    path("panell/afegir-gat", views.add_cat, name="add_cat"),
    path("panell/afegir-gos", views.add_dog, name="add_dog"),
    path("panell/editar-gat/<int:pet_id>", views.edit_pet, name="edit_cat"),
    path("panell/editar-gos/<int:pet_id>", views.edit_pet, name="edit_dog"),
    path("panell/eliminar-imatge-gat/<int:pk>", views.DeleteCatPicture.as_view(), name="delete_cat_picture"),
    path("panell/eliminar-imatge-gos/<int:pk>", views.DeleteDogPicture.as_view(), name="delete_dog_picture"),
    path(
        "panell/eliminar-peticio-adopcio/<int:pk>",
        views.DeleteAdoptionRequest.as_view(),
        name="delete_adoption_request",
    ),
]

amicpelut/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
import adoptions.sitemaps as adoptions_sitemaps
import organizations.sitemaps as organizations_sitemaps
from amicpelut import settings
from . import views


urlpatterns = (
    i18n_patterns(
        path("", include("core.urls")),
        path("", include("organizations.urls")),
        path("", include("adoptions.urls")),
        path("admin/", admin.site.urls),
        prefix_default_language=False,
    )
    + [
        path(
            "sitemap.xml",
            sitemap,
            {
                "sitemaps": {
                    "protectores": organizations_sitemaps.OrganizationSitemap,
                    "animals": adoptions_sitemaps.PetSitemap,
                }
            },
            name="sitemap",
        ),
        path("robots.txt", views.robots_txt, name="robots"),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)


handler404 = views.not_found_handler
handler500 = views.internal_error_handler


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("500", views.internal_error_handler, name="internal_error"),
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

core/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("sobre-nosaltres", views.about, name="about"),
    path("contacte", views.send_contact_email, name="send_contact_email"),
    path("panell", views.dashboard, name="dashboard"),
    path(
        "usuari/entrar", LoginView.as_view(template_name="core/users/login.html", success_url="dashboard"), name="login"
    ),
    path("usuari/sortir", views.logout_view, name="logout"),
]

adoptions/models.py
from datetime import datetime, timezone
from django.db import models
from django.utils.translation import gettext_lazy as _, ngettext, gettext
from uuid import uuid4
from django_resized import ResizedImageField
from django.utils.text import slugify

from organizations.models import Organization


class Trait(models.Model):
    name = models.CharField(max_length=32, verbose_name=_("Nom"))
    description = models.TextField(null=True, blank=True, verbose_name=_("Descripció"))
    positive = models.BooleanField(verbose_name=_("Positiva"))
    applies_to_cats = models.BooleanField(default=True, verbose_name=_("Vàlid per gats"))
    applies_to_dogs = models.BooleanField(default=True, verbose_name=_("Vàlid per gossos"))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-positive", "name")
        verbose_name = _("Característica")
        verbose_name_plural = _("Característiques")


class Pet(models.Model):
    class Sex(models.TextChoices):
        FEMALE = "FEMALE", _("Femella")
        MALE = "MALE", _("Mascle")

    class Size(models.TextChoices):
        MINI = "MINI", _("Mini")
        SMALL = "SMALL", _("Petita")
        MEDIUM = "MEDIUM", _("Mitjana")
        BIG = "BIG", _("Gran")
        VERY_BIG = "VERY_BIG", _("Molt gran")

    class Type(models.TextChoices):
        CAT = "CAT", _("Gat")
        DOG = "DOG", _("Gos")

    name = models.CharField(max_length=32, verbose_name=_("Nom"))
    description = models.TextField(verbose_name=_("Descripció"))
    birth_date = models.DateField(verbose_name=_("Data de naixement"))
    type = models.CharField(max_length=16, choices=Type.choices, null=False, blank=False, verbose_name=_("Tipus"),)
    race = models.CharField(max_length=32, verbose_name=_("Raça"))
    sex = models.CharField(max_length=6, choices=Sex.choices, verbose_name=_("Sexe"))
    size = models.CharField(max_length=16, choices=Size.choices, verbose_name=_("Mida"))
    traits = models.ManyToManyField(Trait, blank=True, verbose_name=_("Característiques"))
    adopted = models.BooleanField(default=False, verbose_name=_("Adoptat"))

    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, verbose_name=_("Organització"))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Creat"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Actualitzat"))

    @property
    def gendered_type(self) -> str:
        if self.type == self.Type.CAT:
            if self.sex == self.Sex.FEMALE:
                return _("Gata")
            return _("Gat")
        if self.sex == self.Sex.FEMALE:
            return _("Gossa")
        return _("Gos")

    @property
    def age(self) -> str:
        today = datetime.today()
        years = today.year - self.birth_date.year
        months = today.month - self.birth_date.month

        if today.day < self.birth_date.day:
            months -= 1
        if months < 0:
            months += 12
            years += 1

        months_text = ngettext("1 mes", "%(months)d mesos" % {"months": months}, months)

        if years > 0:
            years_text = ngettext("1 any", "%(years)d anys" % {"years": years}, years)
            if months == 0:
                return years_text
            return _("%(years_text)s i %(months_text)s" % {"years_text": years_text, "months_text": months_text})
        if months > 0:
            return months_text

        days = (today.date() - self.birth_date).days
        return ngettext("1 dia", "%(days)d dies" % {"days": days}, days)

    @property
    def days_since_creation(self) -> int:
        return (datetime.now(timezone.utc) - self.created_at).days

    def get_share_text(self) -> str:
        return _(
            "%(name)s: %(type)s en adopció! %(description)s"
            % {"name": self.name, "type": self.gendered_type, "description": self.description}
        )

    def get_absolute_url(self) -> str:
        if self.type == self.Type.CAT:
            return f"/gat/{self.id}/{slugify(self.name)}"
        return f"/gos/{self.id}/{slugify(self.name)}"

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Animal")
        verbose_name_plural = _("Animals")


def pet_picture_path(instance, filename):
    return f"pets/{instance.pet.id}/{uuid4().hex}/{filename}"


class PetPicture(models.Model):
    picture = ResizedImageField(upload_to=pet_picture_path, verbose_name=_("Foto"))
    pet = models.ForeignKey(Pet, related_name="pictures", on_delete=models.CASCADE, verbose_name=_("Imatges"))

    def __str__(self):
        return self.picture.name

    class Meta:
        verbose_name = _("Foto")
        verbose_name_plural = _("Fotos")


class AdoptionRequest(models.Model):
    name = models.CharField(max_length=128, verbose_name=_("Nom i cognoms"))
    email = models.EmailField(verbose_name=_("Email"))
    text = models.TextField(null=True, blank=True, verbose_name=_("Missatge"))
    pet = models.ForeignKey(Pet, related_name="adoption_requests", on_delete=models.CASCADE, verbose_name=_("Animal"))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Data"))

    def __str__(self):
        return gettext(
            "Petició de %(requester_name)s per %(pet_name)s" % {"requester_name": self.name, "pet_name": self.pet.name}
        )

    class Meta:
        verbose_name = _("Petició d'adopció")
        verbose_name_plural = _("Peticions d'adopció")

adoptions/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DeleteView, ListView
from django.core.paginator import Paginator
from django.utils.text import slugify

from adoptions.forms import PetForm, PetSearchForm, AdoptionRequestForm
from adoptions.models import Pet, PetPicture, Trait, AdoptionRequest

PETS_PER_PAGE = 20


def home(request: HttpRequest) -> HttpResponse:
    types = request.GET.getlist(key="type", default=[type.name for type in Pet.Type])
    sexes = request.GET.getlist(key="sex", default=[sex.name for sex in Pet.Sex])
    sizes = request.GET.getlist(key="size", default=[size.name for size in Pet.Size])

    pet_list = Pet.objects.filter(adopted=False, type__in=types, sex__in=sexes, size__in=sizes)

    filter_count = len(
        request.GET.getlist(key="type", default=[])
        + request.GET.getlist(key="sex", default=[])
        + request.GET.getlist(key="size", default=[])
    )

    paginator = Paginator(pet_list, PETS_PER_PAGE)
    page = request.GET.get("p", 1)
    pets = paginator.get_page(page)

    form = PetSearchForm(request.GET)

    return render(request, "pets/home.html", {"pets": pets, "form": form, "filter_count": filter_count})


def cats(request: HttpRequest) -> HttpResponse:
    pet_list = Pet.objects.filter(type=Pet.Type.CAT.name, adopted=False)
    paginator = Paginator(pet_list, PETS_PER_PAGE)
    page = request.GET.get("p", 1)
    pets = paginator.get_page(page)
    return render(request, "pets/cats.html", {"section": "cats", "pets": pets})


def cat_detail(request: HttpRequest, pet_id: int, pet_slug: str) -> HttpResponse:
    cat = get_object_or_404(Pet, pk=pet_id)
    if pet_slug != slugify(cat.name):
        return redirect(cat.get_absolute_url())

    if request.method == "POST":
        adoption_request_form = AdoptionRequestForm(request.POST)
        if adoption_request_form.is_valid():
            adoption_request = adoption_request_form.save(commit=False)
            adoption_request.pet = cat
            adoption_request.save()
            messages.success(request, message=_("Adopció demanada!"))
            return redirect(cat.get_absolute_url())
        else:
            messages.error(request, message=_("No s'ha pogut fer la petició d'adopció. Sisplau, intenta-ho més tard."))
    else:
        adoption_request_form = AdoptionRequestForm()

    return render(
        request, "pets/pet_detail.html", {"section": "cats", "pet": cat, "adoption_request_form": adoption_request_form}
    )


def dogs(request: HttpRequest) -> HttpResponse:
    pet_list = Pet.objects.filter(type=Pet.Type.DOG.name, adopted=False)
    paginator = Paginator(pet_list, PETS_PER_PAGE)
    page = request.GET.get("p", 1)
    pets = paginator.get_page(page)
    return render(request, "pets/dogs.html", {"section": "dogs", "pets": pets})


def dog_detail(request: HttpRequest, pet_id: int, pet_slug: str) -> HttpResponse:
    dog = get_object_or_404(Pet, pk=pet_id)
    if pet_slug != slugify(dog.name):
        return redirect(dog.get_absolute_url())

    if request.method == "POST":
        adoption_request_form = AdoptionRequestForm(request.POST)
        if adoption_request_form.is_valid():
            adoption_request = adoption_request_form.save(commit=False)
            adoption_request.pet = dog
            adoption_request.save()
            messages.success(request, message=_("Adopció demanada!"))
            return redirect(dog.get_absolute_url())
        else:
            messages.error(request, message=_("No s'ha pogut fer la petició d'adopció. Sisplau, intenta-ho més tard."))
    else:
        adoption_request_form = AdoptionRequestForm()

    return render(
        request, "pets/pet_detail.html", {"section": "dogs", "pet": dog, "adoption_request_form": adoption_request_form}
    )


class AdoptedPets(ListView):
    queryset = Pet.objects.filter(adopted=True)
    paginate_by = PETS_PER_PAGE
    context_object_name = "pets"
    template_name = "pets/adopted.html"
    extra_context = {"section": "adopted"}


@login_required()
@csrf_protect
def adopt_pet(request: HttpRequest, pet_id: int) -> HttpResponse:
    pet = get_object_or_404(Pet, pk=pet_id)
    pet.adopted = True
    pet.save()
    messages.success(request, _("Desat correctament!"))
    return redirect(to="core:dashboard")


@login_required()
@csrf_protect
def cancel_pet_adoption(request: HttpRequest, pet_id: int) -> HttpResponse:
    pet = get_object_or_404(Pet, pk=pet_id)
    pet.adopted = False
    pet.save()
    messages.success(request, _("Desat correctament!"))
    return redirect(to="core:dashboard")


def _get_traits(trait_ids: list) -> list:
    return Trait.objects.filter(pk__in=trait_ids)


def _create_request_pictures(request: HttpRequest, pet: Pet):
    pictures = request.FILES.getlist(key="pictures")
    for picture in pictures:
        PetPicture.objects.create(picture=picture, pet=pet)


def _add_pet(request: HttpRequest, pet_type: Pet.Type) -> HttpResponse:
    status_code = 200
    if request.method == "POST":
        form = PetForm(request.POST, type=pet_type.name)
        if form.is_valid():
            pet = form.save(commit=False)
            pet.type = pet_type.name
            pet.organization = request.user.adoptions.organization
            pet.save()

            pet.traits.set(_get_traits(form.cleaned_data["traits"]))

            _create_request_pictures(request, pet)

            return redirect(pet.get_absolute_url())
        else:
            status_code = 400

    form = PetForm(type=pet_type.name)
    return render(request, "pets/pet_form.html", {"form": form, "pet_type": pet_type}, status=status_code)


@login_required()
@csrf_protect
def add_cat(request: HttpRequest) -> HttpResponse:
    return _add_pet(request, Pet.Type.CAT)


@login_required()
@csrf_protect
def add_dog(request: HttpRequest) -> HttpResponse:
    return _add_pet(request, Pet.Type.DOG)


@login_required()
@csrf_protect
def edit_pet(request: HttpRequest, pet_id: int) -> HttpResponse:
    pet = get_object_or_404(Pet, pk=pet_id)

    status = 200

    if request.method == "POST":
        form = PetForm(request.POST, instance=pet, type=pet.type)
        if form.is_valid():
            pet = form.save(commit=False)
            pet.save()

            pet.traits.set(_get_traits(form.cleaned_data["traits"]))

            _create_request_pictures(request, pet)

            return redirect(pet.get_absolute_url())
        else:
            status = 400

    form = PetForm(instance=pet, type=pet.type)
    return render(request, "pets/pet_form.html", {"pet": pet, "form": form}, status=status)


class DeleteCatPicture(LoginRequiredMixin, DeleteView):
    model = PetPicture

    def get_success_url(self):
        return reverse_lazy("adoptions:edit_cat", kwargs={"pet_id": self.object.pet.id})


class DeleteDogPicture(LoginRequiredMixin, DeleteView):
    model = PetPicture

    def get_success_url(self):
        return reverse_lazy("adoptions:edit_dog", kwargs={"pet_id": self.object.pet.id})


class DeleteAdoptionRequest(LoginRequiredMixin, DeleteView):
    model = AdoptionRequest

    def get_success_url(self):
        return reverse_lazy("core:dashboard")

adoptions/templates/pets/adopt_pet_modal.html
{% load i18n %}
{% load bootstrap4 %}

<div class="modal fade" id="adoptPetModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <form method="post">
      {% csrf_token %}

      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" id="modalLabel">
            {% blocktrans with pet_name=pet.name %}
              Demanar adopció: {{ pet_name }}
            {% endblocktrans %}
          </h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>
            {% blocktrans with organization_name=pet.organization.name responsible_name=pet.organization.responsibles.first.user.get_full_name %}
              Necessitem algunes dades teves per demanar l'adopció a la protectora <strong>{{ organization_name }}</strong>.
              La seva persona responsable (<strong>{{ responsible_name }}</strong>) es posarà en contacte amb tu el més aviat possible.
            {% endblocktrans %}
          </p>

          {% bootstrap_form form %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Cancel·lar" %}</button>
          <button type="submit" class="btn btn-primary">{% trans "Demanar adopció" %}</button>
        </div>
      </div>
    </form>
  </div>
</div>

adoptions/templates/pets/adopted.html
{% extends "core/layout.html" %}

{% load i18n %}

{% block content %}
  {% if paginator.count > 0 %}
    <h1>{% trans "Nosaltres ja hem trobat una llar!" %}</h1>
    {% include "components/pet_list.html" %}
  {% else %}
    <h1>{% trans "Adoptats" %}</h1>
    <p class="text-muted font-italic">{% trans "Encara no hi ha cap animal adoptat. Algun ha de ser el primer!" %}</p>
  {% endif %}
{% endblock %}

adoptions/templates/pets/dogs.html
{% extends 'core/layout.html' %}

{% load i18n %}

{% block title %}
  {% trans "Gossos - Amic Pelut" %}
{% endblock %}

{% block content %}
  <h1>Gossos en adopció</h1>

  {% include 'components/pet_list.html' %}
{% endblock %}

adoptions/templates/pets/pet_detail.html
{% extends 'core/layout.html' %}

{% load i18n %}
{% load social_share %}
{% load custom_filters %}

{% block title %}
  {% blocktrans with pet_name=pet.name %}
    {{ pet_name }} - Amic Pelut
  {% endblocktrans %}
{% endblock %}

{% block head %}
  {% include "pets/markup/facebook.html" %}
  {% include "pets/markup/twitter.html" %}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6">
        {% if pet.pictures.count == 1 %}
          <img src="{{ MEDIA_URL }}{{ pet.pictures.first }}" alt="" class="w-100"/>
        {% elif pet.pictures.count > 1 %}
          {% include "pets/pet_pictures.html" %}
        {% endif %}
      </div>
      <div class="col-12 col-md-6">
        <h2>{{ pet.name }}</h2>
        <div class="mb-3 h5">
          <span class="badge badge-info mb-1">
            {% if pet.sex == 'FEMALE' %}
              <i class="fa fa-venus"></i>
            {% else %}
              <i class="fa fa-mars"></i>
            {% endif %}
            {{ pet.get_sex_display }}
          </span>
          <span
              class="badge badge-info mb-1"
              data-toggle="tooltip"
              data-position="top"
              title="{% blocktrans with birth_date=pet.birth_date %}Data de naixement: {{ birth_date }}{% endblocktrans %}"
          >
            <i class="far fa-calendar-alt"></i>
            {{ pet.age }}
          </span>
          <span class="badge badge-info mb-1">
            {% if pet.type == 'CAT' %}
              <i class="fas fa-cat"></i>
            {% else %}
              <i class="fas fa-dog"></i>
            {% endif %}
            {% blocktrans with race=pet.race %}Raça: {{ race }}{% endblocktrans %}
          </span>
          <span class="badge badge-info mb-1">
            <i class="fa fa-expand-arrows-alt"></i>
            {% blocktrans with size=pet.get_size_display %}Mida {{ size }}{% endblocktrans %}
          </span>
        </div>

        {% if not pet.adopted %}
          <p>{% blocktrans with timesince=pet.created_at|timesince %}En adopció des de fa: {{ timesince }}{% endblocktrans %}</p>
        {% else %}
          <p class="h5">
            <span class="badge badge-success">
              {% trans "Ja he trobat llar!" %}
            </span>
          </p>
        {% endif %}

        <h3 class="sr-only">{% trans "Descripció" %}</h3>
        <div>{{ pet.description|linebreaks|urlize_target_blank }}</div>

        {% if pet.traits.count %}
          <h3>{% trans "Informació" %}</h3>
          <p class="h5 pb-3">
            {% for trait in pet.traits.all %}
              {% if trait.positive %}
                <span
                    class="badge badge-success mb-1"
                  {% if trait.description %}
                    data-toggle="tooltip"
                    data-placement="top"
                    title="{{ trait.description }}"
                  {% endif %}
                >
                  <i class="fa fa-check"></i>
                  {{ trait.name }}
                </span>
              {% else %}
                <span
                    class="badge badge-warning mb-1"
                  {% if trait.description %}
                    data-toggle="tooltip"
                    data-placement="top"
                    title="{{ trait.description }}"
                  {% endif %}
                >
                  <i class="fa fa-exclamation-triangle"></i>
                  {{ trait.name }}
                </span>
              {% endif %}
            {% endfor %}
          </p>
        {% endif %}

        {% if not pet.adopted %}
          <div class="mb-3">
            <h5>{% trans "Ajuda'm a trobar una família!" %}</h5>
            <div class="mb-3">
              <button class="btn btn-primary btn-action" data-toggle="modal" data-target="#adoptPetModal">
                <i class="fa fa-paw"></i>
                {% trans "Adopta'm!" %}
              </button>
              {% include "pets/adopt_pet_modal.html" with form=adoption_request_form %}
            </div>

            <div class="d-flex mb-3">
              {% post_to_facebook_url pet as context %}
              {% post_to_twitter_url pet.get_share_text pet as context %}

              <div class="mr-1" style="width: 2.5em" data-toggle="tooltip" title="{% trans "Compartir a Facebook" %}">
                <a href="{{ context.facebook_url }}" target="_blank" class="btn btn-primary border-0 w-100" style="background-color: #385898">
                  <i class="fab fa-facebook-f text-white"></i>
                  <span class="sr-only">{% trans "Compartir a Twitter" %}</span>
                </a>
              </div>
              <div class="mr-1" style="width: 2.5em" data-toggle="tooltip" title="{% trans "Compartir a Twitter" %}">
                <a href="{{ context.tweet_url }}" target="_blank" class="btn btn-primary border-0 w-100" style="background-color: #00aced">
                  <i class="fab fa-twitter text-white"></i>
                  <span class="sr-only">{% trans "Compartir a Twitter" %}</span>
                </a>
              </div>
            </div>
          </div>

          <div class="card border-success">
            <div class="row no-gutters">
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">
                    {% blocktrans with organization_name=pet.organization.name organization_url=pet.organization.get_absolute_url %}
                      M'estan cuidant a <a href="{{ organization_url }}">{{ organization_name }}</a>
                    {% endblocktrans %}
                  </h5>
                  <p class="card-text">
                    {% include "organizations/components/contact.html" with organization=pet.organization %}
                  </p>
                </div>
              </div>
              {% if pet.organization.logo %}
                <div class="col-md-4">
                  <a href="{{ pet.organization.get_absolute_url }}">
                    <img src="{{ MEDIA_URL }}{{ pet.organization.logo }}" alt="" class="card-img"/>
                  </a>
                </div>
              {% endif %}
            </div>
          </div>
        {% endif %}

      </div>
    </div>
  </div>
{% endblock %}

adoptions/templates/pets/pet_form.html
{% extends "core/layout.html" %}

{% load i18n %}
{% load bootstrap4 %}

{% block content %}
  <h1>
    {% if pet %}
      {% blocktrans with name=pet.name %}
        Editar {{ name }}
      {% endblocktrans %}
    {% else %}
      {% blocktrans with type=pet_type.value|lower %}
        Afegir {{ type }}
      {% endblocktrans %}
    {% endif %}
  </h1>

  {% bootstrap_form_errors form %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout="horizontal" %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        <i class="fa fa-save"></i>
        {% trans "Desar" %}
      </button>
    {% endbuttons %}
  </form>

  {% if pet.pictures.count > 0 %}
    <div class="pt-3 border-top">
      <h2>{% trans "Fotos" %}</h2>
      <div class="card-columns">
        {% for picture in pet.pictures.all %}
          <div class="card">
            <img src="{{ MEDIA_URL }}{{ picture }}" alt="" style="width: 100%"/>

            <form
                action="
                  {% if pet.type.name == "CAT" %}
                    {% url "adoptions:delete_cat_picture" pk=picture.pk %}
                  {% else %}
                    {% url "adoptions:delete_dog_picture" pk=picture.pk %}
                  {% endif %}
                "
                method="post"
                style="position: absolute; top: 1em; right: 1em"
            >
              {% csrf_token %}

              <div data-toggle="tooltip" data-placement="top" title="{% trans "Eliminar foto" %}">
                <button
                    type="button"
                    class="btn btn-danger"
                    data-toggle="modal"
                    data-target="#deletePictureModal{{ forloop.counter0 }}"
                >
                  <i class="fa fa-trash"></i>
                </button>
              </div>

              <div class="modal fade" id="deletePictureModal{{ forloop.counter0 }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">{% trans "Eliminar foto?" %}</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      {% trans "Estàs segur que vols esborrar aquesta foto? Aquesta acció no es pot desfer." %}
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Cancel·lar" %}</button>
                      <button type="submit" class="btn btn-danger">{% trans "Eliminar" %}</button>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}
{% endblock %}