adoptions/urls.py
from django.urls import path

from adoptions import views

app_name = "adoptions"

urlpatterns = [
    path("gats", views.cats, name="cats"),
    path("gat/<int:pet_id>/<str:pet_slug>", views.cat_detail, name="cat_detail"),
    path("gossos", views.dogs, name="dogs"),
    path("gos/<int:pet_id>/<str:pet_slug>", views.dog_detail, name="dog_detail"),
    path("adoptats", views.AdoptedPets.as_view(), name="adopted"),
    path("adoptar/<int:pet_id>", views.adopt_pet, name="adopt_pet"),
    path("cancelar-adopcio/<int:pet_id>", views.cancel_pet_adoption, name="cancel_pet_adoption"),
    path("panell/afegir-gat", views.add_cat, name="add_cat"),
    path("panell/afegir-gos", views.add_dog, name="add_dog"),
    path("panell/editar-gat/<int:pet_id>", views.edit_pet, name="edit_cat"),
    path("panell/editar-gos/<int:pet_id>", views.edit_pet, name="edit_dog"),
    path("panell/eliminar-imatge-gat/<int:pk>", views.DeleteCatPicture.as_view(), name="delete_cat_picture"),
    path("panell/eliminar-imatge-gos/<int:pk>", views.DeleteDogPicture.as_view(), name="delete_dog_picture"),
    path(
        "panell/eliminar-peticio-adopcio/<int:pk>",
        views.DeleteAdoptionRequest.as_view(),
        name="delete_adoption_request",
    ),
]

amicpelut/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
import adoptions.sitemaps as adoptions_sitemaps
import organizations.sitemaps as organizations_sitemaps
from amicpelut import settings
from . import views


urlpatterns = (
    i18n_patterns(
        path("", include("core.urls")),
        path("", include("organizations.urls")),
        path("", include("adoptions.urls")),
        path("admin/", admin.site.urls),
        prefix_default_language=False,
    )
    + [
        path(
            "sitemap.xml",
            sitemap,
            {
                "sitemaps": {
                    "protectores": organizations_sitemaps.OrganizationSitemap,
                    "animals": adoptions_sitemaps.PetSitemap,
                }
            },
            name="sitemap",
        ),
        path("robots.txt", views.robots_txt, name="robots"),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)


handler404 = views.not_found_handler
handler500 = views.internal_error_handler


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("500", views.internal_error_handler, name="internal_error"),
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

core/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("sobre-nosaltres", views.about, name="about"),
    path("contacte", views.send_contact_email, name="send_contact_email"),
    path("panell", views.dashboard, name="dashboard"),
    path(
        "usuari/entrar", LoginView.as_view(template_name="core/users/login.html", success_url="dashboard"), name="login"
    ),
    path("usuari/sortir", views.logout_view, name="logout"),
]

organizations/urls.py
from django.urls import path

from organizations import views

app_name = "organizations"

urlpatterns = [
    path("protectores", views.organizations, name="organizations"),
    path("protectora/<int:pk>/<str:slug>", views.OrganizationDetail.as_view(), name="organization_detail"),
    path("panell/editar-protectora/<int:pk>", views.UpdateOrganization.as_view(), name="edit_organization"),
]

adoptions/models.py
from datetime import datetime, timezone
from django.db import models
from django.utils.translation import gettext_lazy as _, ngettext, gettext
from uuid import uuid4
from django_resized import ResizedImageField
from django.utils.text import slugify

from organizations.models import Organization


class Trait(models.Model):
    name = models.CharField(max_length=32, verbose_name=_("Nom"))
    description = models.TextField(null=True, blank=True, verbose_name=_("Descripció"))
    positive = models.BooleanField(verbose_name=_("Positiva"))
    applies_to_cats = models.BooleanField(default=True, verbose_name=_("Vàlid per gats"))
    applies_to_dogs = models.BooleanField(default=True, verbose_name=_("Vàlid per gossos"))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-positive", "name")
        verbose_name = _("Característica")
        verbose_name_plural = _("Característiques")


class Pet(models.Model):
    class Sex(models.TextChoices):
        FEMALE = "FEMALE", _("Femella")
        MALE = "MALE", _("Mascle")

    class Size(models.TextChoices):
        MINI = "MINI", _("Mini")
        SMALL = "SMALL", _("Petita")
        MEDIUM = "MEDIUM", _("Mitjana")
        BIG = "BIG", _("Gran")
        VERY_BIG = "VERY_BIG", _("Molt gran")

    class Type(models.TextChoices):
        CAT = "CAT", _("Gat")
        DOG = "DOG", _("Gos")

    name = models.CharField(max_length=32, verbose_name=_("Nom"))
    description = models.TextField(verbose_name=_("Descripció"))
    birth_date = models.DateField(verbose_name=_("Data de naixement"))
    type = models.CharField(max_length=16, choices=Type.choices, null=False, blank=False, verbose_name=_("Tipus"),)
    race = models.CharField(max_length=32, verbose_name=_("Raça"))
    sex = models.CharField(max_length=6, choices=Sex.choices, verbose_name=_("Sexe"))
    size = models.CharField(max_length=16, choices=Size.choices, verbose_name=_("Mida"))
    traits = models.ManyToManyField(Trait, blank=True, verbose_name=_("Característiques"))
    adopted = models.BooleanField(default=False, verbose_name=_("Adoptat"))

    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, verbose_name=_("Organització"))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Creat"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Actualitzat"))

    @property
    def gendered_type(self) -> str:
        if self.type == self.Type.CAT:
            if self.sex == self.Sex.FEMALE:
                return _("Gata")
            return _("Gat")
        if self.sex == self.Sex.FEMALE:
            return _("Gossa")
        return _("Gos")

    @property
    def age(self) -> str:
        today = datetime.today()
        years = today.year - self.birth_date.year
        months = today.month - self.birth_date.month

        if today.day < self.birth_date.day:
            months -= 1
        if months < 0:
            months += 12
            years += 1

        months_text = ngettext("1 mes", "%(months)d mesos" % {"months": months}, months)

        if years > 0:
            years_text = ngettext("1 any", "%(years)d anys" % {"years": years}, years)
            if months == 0:
                return years_text
            return _("%(years_text)s i %(months_text)s" % {"years_text": years_text, "months_text": months_text})
        if months > 0:
            return months_text

        days = (today.date() - self.birth_date).days
        return ngettext("1 dia", "%(days)d dies" % {"days": days}, days)

    @property
    def days_since_creation(self) -> int:
        return (datetime.now(timezone.utc) - self.created_at).days

    def get_share_text(self) -> str:
        return _(
            "%(name)s: %(type)s en adopció! %(description)s"
            % {"name": self.name, "type": self.gendered_type, "description": self.description}
        )

    def get_absolute_url(self) -> str:
        if self.type == self.Type.CAT:
            return f"/gat/{self.id}/{slugify(self.name)}"
        return f"/gos/{self.id}/{slugify(self.name)}"

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Animal")
        verbose_name_plural = _("Animals")


def pet_picture_path(instance, filename):
    return f"pets/{instance.pet.id}/{uuid4().hex}/{filename}"


class PetPicture(models.Model):
    picture = ResizedImageField(upload_to=pet_picture_path, verbose_name=_("Foto"))
    pet = models.ForeignKey(Pet, related_name="pictures", on_delete=models.CASCADE, verbose_name=_("Imatges"))

    def __str__(self):
        return self.picture.name

    class Meta:
        verbose_name = _("Foto")
        verbose_name_plural = _("Fotos")


class AdoptionRequest(models.Model):
    name = models.CharField(max_length=128, verbose_name=_("Nom i cognoms"))
    email = models.EmailField(verbose_name=_("Email"))
    text = models.TextField(null=True, blank=True, verbose_name=_("Missatge"))
    pet = models.ForeignKey(Pet, related_name="adoption_requests", on_delete=models.CASCADE, verbose_name=_("Animal"))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Data"))

    def __str__(self):
        return gettext(
            "Petició de %(requester_name)s per %(pet_name)s" % {"requester_name": self.name, "pet_name": self.pet.name}
        )

    class Meta:
        verbose_name = _("Petició d'adopció")
        verbose_name_plural = _("Peticions d'adopció")

organizations/models.py
from django.contrib.gis.geos import Point
from django.db import models
from django_resized import ResizedImageField
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from location_field.models.spatial import LocationField

from core.models import User


def organization_logo_path(instance, filename):
    return f"organizations/{instance.id}/{filename}"


class Organization(models.Model):
    name = models.CharField(max_length=64, verbose_name=_("Nom"))
    description = models.TextField(verbose_name=_("Descripció"))
    logo = ResizedImageField(upload_to=organization_logo_path, verbose_name=_("Logo"), null=True, blank=True)

    website = models.CharField(max_length=32, blank=True, verbose_name=_("Pàgina web"))
    email = models.EmailField(blank=True, verbose_name=_("Correu electrònic"))
    telephone = models.CharField(max_length=32, blank=True, verbose_name=_("Telèfon"))

    enable_notifications = models.BooleanField(default=True, verbose_name=_("Rebre notificacions"))

    address = models.CharField(max_length=512, blank=True, verbose_name=_("Adreça"))
    city = models.CharField(max_length=64, blank=True, verbose_name=_("Ciutat"))
    location = LocationField(
        based_fields=["address", "city"], default=Point(41.9780841, 2.8196819), verbose_name=_("Localització")
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Creat"))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Actualitzat"))

    def get_share_text(self) -> str:
        return _("%(name)s: %(description)s" % {"name": self.name, "description": self.description})

    def get_absolute_url(self):
        return f"/protectora/{self.id}/{slugify(self.name)}"

    def location_str(self):
        return f"{self.location.y},{self.location.x}"

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Organització")
        verbose_name_plural = _("Organitzacions")
        ordering = ("name",)


class OrganizationResponsible(models.Model):
    user = models.OneToOneField(User, related_name="adoptions", on_delete=models.CASCADE, verbose_name=_("Usuari"))
    organization = models.ForeignKey(
        Organization,
        related_name="responsibles",
        related_query_name="responsible",
        on_delete=models.CASCADE,
        verbose_name=_("Organització"),
    )

    class Meta:
        verbose_name = _("Adopcions")
        verbose_name_plural = _("Adopcions")

organizations/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from organizations.models import Organization


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = (
            "name",
            "description",
            "logo",
            "address",
            "city",
            "location",
            "website",
            "telephone",
            "email",
            "enable_notifications",
        )
        help_texts = {
            "enable_notifications": _(
                "Si configures la direcció de correu, rebràs una notificació quan algú vulgui adoptar un dels vostres "
                "animals. "
            )
        }

organizations/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic import UpdateView, DetailView
from django.core.paginator import Paginator
from django.utils.text import slugify

from adoptions.models import Pet
from organizations.forms import OrganizationForm
from organizations.models import Organization

PETS_PER_PAGE = 20


def organizations(request: HttpRequest) -> HttpResponse:
    organizations = Organization.objects.all()
    organizations_json = json.dumps(
        [
            {
                "id": org.id,
                "name": org.name,
                "slug": slugify(org.name),
                "latitude": org.location.y,
                "longitude": org.location.x,
            }
            for org in organizations
            if org.location
        ]
    )
    return render(
        request,
        "organizations/organization_list.html",
        {"section": "organizations", "organizations": organizations, "organizations_json": organizations_json},
    )


@method_decorator(login_required, name="dispatch")
@method_decorator(csrf_protect, name="dispatch")
class UpdateOrganization(UserPassesTestMixin, UpdateView):
    model = Organization
    template_name = "organizations/organization_form.html"
    form_class = OrganizationForm

    def test_func(self):
        return self.request.user.adoptions.organization.id == self.kwargs["pk"]


class OrganizationDetail(DetailView):
    model = Organization
    template_name = "organizations/organization_detail.html"
    context_object_name = "organization"

    def get(self, request, *args, **kwargs):
        response = super().get(request, args, **kwargs)
        slug = kwargs.get("slug")
        if slug != slugify(self.object.name):
            return redirect(self.object.get_absolute_url())
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        pet_list = Pet.objects.filter(organization_id__exact=self.object.pk, adopted=False)
        paginator = Paginator(pet_list, PETS_PER_PAGE)
        page = self.request.GET.get("p", 1)
        pets = paginator.get_page(page)
        context["pets"] = pets
        context["adopted_pets"] = Pet.objects.filter(organization_id__exact=self.object.pk, adopted=True)[:3]
        context["section"] = "organizations"
        return context

organizations/templates/organizations/components/contact.html
{% load i18n %}

<p>
  <strong>{% trans "Responsable: " %}</strong>
  {{ organization.responsibles.first.user.first_name }}
  {{ organization.responsibles.first.user.last_name }}
</p>

{% if organization.address or organization.city or organization.location %}
  {% include "organizations/components/location.html" %}
{% endif %}

{% if organization.website %}
  <div>
    <a href="{{ organization.website }}" target="_blank">
      <i class="fas fa-external-link-alt"></i>
      {{ organization.website }}
    </a>
  </div>
{% endif %}

{% if organization.email %}
  <div>
    <a href="mailto:{{ organization.email }}">
      <i class="far fa-envelope"></i>
      {{ organization.email }}
    </a>
  </div>
{% endif %}

{% if organization.telephone %}
  <div>
    <a href="tel:{{ organization.telephone }}">
      <i class="fa fa-phone"></i>
      {{ organization.telephone }}
    </a>
  </div>
{% endif %}

organizations/templates/organizations/components/location.html
{% load i18n %}

{% if organization.location %}
  <a href="https://www.google.com/maps/search/?api=1&query={{ organization.location_str }}" target="_blank" rel="noopener noreferrer">
{% endif %}

<i class="fa fa-map-marker-alt"></i>

{% if organization.address %}
  {{ organization.address }}{% if organization.city %}, {{ organization.city }}{% endif %}
{% else %}
  {% if organization.city %}
    {{ organization.city }}
  {% else %}
    {% trans "Veure mapa" %}
  {% endif %}
{% endif %}

{% if organization.location %}
  </a>
{% endif %}

organizations/templates/organizations/components/map_marker.html
{% load custom_filters %}

<div class="d-flex justify-content-between">
  <div>
    <h4>
      <a href="{{ organization.get_absolute_url }}">{{ organization.name }}</a>
    </h4>
    <div>
      {{ organization.description|linebreaks|truncatewords_html:20|urlize_target_blank }}
    </div>
  </div>
  {% if organization.logo %}
    <div class="ml-3 mt-1 mr-1 mb-1">
      <a href="{{ organization.get_absolute_url }}">
        <img src="{{ MEDIA_URL }}{{ organization.logo }}" alt="" class="card-img-top" style="width: 150px"/>
      </a>
    </div>
  {% endif %}
</div>

organizations/templates/organizations/components/pet_adoption_requests.html
{% load i18n %}

<div class="modal fade" id="adoptionRequestsModal{{ pet.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">
          {% blocktrans with pet_name=pet.name %}
            Peticions d'adopció: {{ pet_name }}
          {% endblocktrans %}
        </h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <table class="table table-responsive-lg">
        <thead>
        <tr class="bg-white">
          <th scope="col">{% trans "Nom" %}</th>
          <th scope="col">{% trans "Email" %}</th>
          <th scope="col">{% trans "Missatge" %}</th>
          <th scope="col">{% trans "Data" %}</th>
          <th scope="col">{% trans "Eliminar" %}</th>
        </tr>
        </thead>
        <tbody>
          {% for adoption_request in pet.adoption_requests.all %}
            <tr class="bg-white">
              <th class="text-nowrap">{{ adoption_request.name }}</th>
              <td>
                <a href="mailto:{{ adoption_request.email }}">
                  {{ adoption_request.email }}
                </a>
              </td>
              <td>{{ adoption_request.text }}</td>
              <td>
                {% blocktrans with date=adoption_request.created_at|date time=adoption_request.created_at|time %}
                  {{ date }} a les {{ time }}
                {% endblocktrans %}
              </td>
              <td class="d-flex justify-content-end">
                <button class="btn btn-secondary" data-toggle="modal" data-target="#deleteAdoptionRequestModal{{ adoption_request.id }}">
                  <i class="fa fa-trash"></i>
                </button>

                <div class="modal fade" id="deleteAdoptionRequestModal{{ adoption_request.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title">{% trans "Eliminar petició d'adopció?" %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        {% trans "Estàs segur que vols esborrar aquesta petició? Aquesta acció no es pot desfer." %}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Cancel·lar" %}</button>
                        <form action="{% url "adoptions:delete_adoption_request" pk=adoption_request.pk %}" method="post" style="margin-bottom: 0">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger">{% trans "Eliminar" %}</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Tancar" %}</button>
      </div>
    </div>
  </div>
</div>

organizations/templates/organizations/components/pet_table.html
{% load i18n %}

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">{% trans "Nom" %}</th>
      <th scope="col">{% trans "Descripció" %}</th>
      <th scope="col">{% trans "Data de naixement" %}</th>
      <th scope="col">{% trans "Raça" %}</th>
      <th scope="col">{% trans "Sexe" %}</th>
      <th scope="col">{% trans "Mida" %}</th>
      <th scope="col">{% trans "Creat" %}</th>
      <th scope="col">{% trans "Adoptat" %}</th>
      <th scope="col">{% trans "Accions" %}</th>
    </tr>
    </thead>
    <tbody>
    {% for pet in pets %}
      <tr>
        <th scope="row">{{ pet.id }}</th>
        <td>{{ pet.name }}</td>
        <td>{{ pet.description|truncatechars:20 }}</td>
        <td>{{ pet.birth_date }}</td>
        <td>{{ pet.race }}</td>
        <td>{{ pet.get_sex_display }}</td>
        <td>{{ pet.get_size_display }}</td>
        <td>{{ pet.created_at|date }}</td>
        <td class="text-center"><input type="checkbox" disabled {% if pet.adopted %}checked{% endif %}/></td>
        <td class="d-flex justify-content-end">
          {% if pet.adoption_requests.count %}
            <div data-toggle="tooltip" title="{% trans "Peticions d'adopció" %}">
              <button type="button" class="btn btn-primary mr-1 text-nowrap" data-toggle="modal" data-target="#adoptionRequestsModal{{ pet.id }}">
                <i class="fas fa-paw mr-1"></i>
               <span class="badge badge-light">
                  {{ pet.adoption_requests.count }}
                </span>
              </button>
              {% include "organizations/components/pet_adoption_requests.html" %}
            </div>
          {% endif %}
          <button
              class="btn btn-secondary dropdown-toggle"
              type="button"
              id="actionsDropdown{{ pet.id }}"
              data-toggle="dropdown"
              aria-haspopup="true"
          >
            <i class="fas fa-tools"></i>
          </button>
          <div class="dropdown-menu" aria-labelledby="actionsDropdown{{ pet.id }}">
            <a
                href="
                  {% if pet.type == "CAT" %}
                    {% url "adoptions:edit_cat" pet_id=pet.id %}
                  {% else %}
                    {% url "adoptions:edit_dog" pet_id=pet.id %}
                  {% endif %}
                "
                class="dropdown-item"
            >
              <i class="fas fa-pencil-alt mr-2"></i>
              {% trans "Editar" %}
            </a>
            {% if pet.adopted %}
             <a href="{% url "adoptions:cancel_pet_adoption" pet_id=pet.id %}" class="dropdown-item">
                <i class="fas fa-heart-broken mr-2"></i>
                <span class="sr-only">
                  {% trans "Marcar com a no adoptat" %}
                </span>
              </a>
            {% else %}
              <a href="{% url "adoptions:adopt_pet" pet_id=pet.id %}" class="dropdown-item">
                <i class="fas fa-heart mr-2"></i>
                {% trans "Marcar com a adoptat" %}
              </a>
            {% endif %}
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>