adoptions/urls.py
from django.urls import path

from adoptions import views

app_name = "adoptions"

urlpatterns = [
    path("gats", views.cats, name="cats"),
    path("gat/<int:pet_id>/<str:pet_slug>", views.cat_detail, name="cat_detail"),
    path("gossos", views.dogs, name="dogs"),
    path("gos/<int:pet_id>/<str:pet_slug>", views.dog_detail, name="dog_detail"),
    path("adoptats", views.AdoptedPets.as_view(), name="adopted"),
    path("adoptar/<int:pet_id>", views.adopt_pet, name="adopt_pet"),
    path("cancelar-adopcio/<int:pet_id>", views.cancel_pet_adoption, name="cancel_pet_adoption"),
    path("panell/afegir-gat", views.add_cat, name="add_cat"),
    path("panell/afegir-gos", views.add_dog, name="add_dog"),
    path("panell/editar-gat/<int:pet_id>", views.edit_pet, name="edit_cat"),
    path("panell/editar-gos/<int:pet_id>", views.edit_pet, name="edit_dog"),
    path("panell/eliminar-imatge-gat/<int:pk>", views.DeleteCatPicture.as_view(), name="delete_cat_picture"),
    path("panell/eliminar-imatge-gos/<int:pk>", views.DeleteDogPicture.as_view(), name="delete_dog_picture"),
    path(
        "panell/eliminar-peticio-adopcio/<int:pk>",
        views.DeleteAdoptionRequest.as_view(),
        name="delete_adoption_request",
    ),
]

amicpelut/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
import adoptions.sitemaps as adoptions_sitemaps
import organizations.sitemaps as organizations_sitemaps
from amicpelut import settings
from . import views


urlpatterns = (
    i18n_patterns(
        path("", include("core.urls")),
        path("", include("organizations.urls")),
        path("", include("adoptions.urls")),
        path("admin/", admin.site.urls),
        prefix_default_language=False,
    )
    + [
        path(
            "sitemap.xml",
            sitemap,
            {
                "sitemaps": {
                    "protectores": organizations_sitemaps.OrganizationSitemap,
                    "animals": adoptions_sitemaps.PetSitemap,
                }
            },
            name="sitemap",
        ),
        path("robots.txt", views.robots_txt, name="robots"),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)


handler404 = views.not_found_handler
handler500 = views.internal_error_handler


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("500", views.internal_error_handler, name="internal_error"),
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

core/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("sobre-nosaltres", views.about, name="about"),
    path("contacte", views.send_contact_email, name="send_contact_email"),
    path("panell", views.dashboard, name="dashboard"),
    path(
        "usuari/entrar", LoginView.as_view(template_name="core/users/login.html", success_url="dashboard"), name="login"
    ),
    path("usuari/sortir", views.logout_view, name="logout"),
]

organizations/urls.py
from django.urls import path

from organizations import views

app_name = "organizations"

urlpatterns = [
    path("protectores", views.organizations, name="organizations"),
    path("protectora/<int:pk>/<str:slug>", views.OrganizationDetail.as_view(), name="organization_detail"),
    path("panell/editar-protectora/<int:pk>", views.UpdateOrganization.as_view(), name="edit_organization"),
]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name=_("Correu electrònic"))

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        ordering = ("id", "email")
        db_table = "auth_user"

core/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Invisible
from django import forms
from django.utils.translation import gettext_lazy as _


class SendContactEmailForm(forms.Form):
    name = forms.CharField(label=_("Nom i cognoms"), widget=forms.TextInput(attrs={"placeholder": _("El teu nom")}))
    email = forms.EmailField(
        label=_("Correu electrònic"), widget=forms.EmailInput(attrs={"placeholder": _("exemple@email.com")})
    )
    message = forms.CharField(widget=forms.Textarea(attrs={"placeholder": ""}), label=_("Missatge"))
    captcha = ReCaptchaField(widget=ReCaptchaV2Invisible, label="", required=True)

core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.translation import gettext_lazy as _

from adoptions import views as adoptions_views
from adoptions.models import Pet
from core.forms import SendContactEmailForm

PETS_PER_PAGE = 20


def home(request: HttpRequest) -> HttpResponse:
    return adoptions_views.home(request)


def about(request: HttpRequest) -> HttpResponse:
    form = SendContactEmailForm()
    return render(request, "core/about/about.html", {"section": "about", "contact_form": form})


def send_contact_email(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = SendContactEmailForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]
            subject = _("%(name)s (Formulari de contacte)" % {"name": form.cleaned_data["name"]})
            body = f"Missatge de {name} ({email}):\n\n{message}"
            msg = EmailMessage(
                from_email=f"{name} <contacte@amicpelut.com>",
                to=["contacte@amicpelut.com"],
                reply_to=[form.cleaned_data["email"]],
                subject=subject,
                body=body,
            )
            msg.send()
            messages.success(request, _("El missatge s'ha enviat correctament."))
        else:
            messages.error(request, _("No s'ha pogut enviar el missatge. Sisplau, torna a intentar-ho més tard."))
    return redirect(to="core:about")


@login_required()
def dashboard(request: HttpRequest) -> HttpResponse:
    organization = request.user.adoptions.organization
    cats = Pet.objects.filter(type=Pet.Type.CAT, organization=organization).order_by("adopted", "pk")
    dogs = Pet.objects.filter(type=Pet.Type.DOG, organization=organization).order_by("adopted", "pk")

    status_code = 200
    if request.method == "POST":
        password_form = PasswordChangeForm(request.user, request.POST)
        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, _("Contrasenya canviada amb èxit!"))
        else:
            messages.error(request, _("No s'ha pogut canviar la contrasenya"))
            status_code = 400
    else:
        password_form = PasswordChangeForm(request.user)

    return render(
        request,
        "core/dashboard.html",
        {"section": "dashboard", "organization": organization, "cats": cats, "dogs": dogs, "user_form": password_form},
        status=status_code,
    )


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    messages.success(request, _("S'ha tancat la sessió correctament."))
    return redirect(to="core:home")

core/templates/core/dashboard.html
{% extends "core/layout.html" %}

{% load i18n %}
{% load bootstrap4 %}
{% load custom_filters %}

{% block title %}
  {% trans "Panell de Control - Amic Pelut" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Panell de control" %}</h1>

  {# To prevent autofocusing on fields below #}
  <input type="hidden" autofocus />

  <h2>{{ organization.name }}</h2>
  <div class="row mb-3 mb-md-0">
    <div class="col-md-8">
      <div>{{ organization.description|linebreaks|urlize_target_blank }}</div>
    </div>
    <div class="col-md-4">
      {% include 'organizations/components/contact.html' %}
    </div>
  </div>

  <a href="{% url "organizations:edit_organization" pk=organization.id %}" class="btn btn-primary">
    <i class="fas fa-pencil-alt"></i>
    {% trans "Editar informació" %}
  </a>

  <hr/>

  {% if cats.count > 0 %}
    <h3>{% trans "Els vostres gats" %}</h3>
    {% include "organizations/components/pet_table.html" with pets=cats %}
  {% endif %}
  <a href="{% url "adoptions:add_cat" %}" class="btn btn-primary mb-3">
    <i class="fa fa-plus"></i>
    {% trans "Afegir gat" %}
  </a>

  {% if dogs.count > 0 %}
    <h3>{% trans "Els vostres gossos" %}</h3>
    {% include "organizations/components/pet_table.html" with pets=dogs %}
  {% endif %}
  <a href="{% url "adoptions:add_dog" %}" class="btn btn-primary mb-3">
    <i class="fa fa-plus"></i>
    {% trans "Afegir gos" %}
  </a>

  <hr/>

  <h2>{% trans "Preferències d'usuari" %}</h2>
  <form method="post">
    {% bootstrap_form user_form layout="horizontal" %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        <i class="fa fa-save"></i>
        {% trans "Canviar contrasenya" %}
      </button>
    {% endbuttons %}
  </form>
{% endblock %}

core/templates/core/footer.html
{% load i18n %}

<div class="d-flex justify-content-center text-muted mt-3" style="font-size: 0.8rem">
  <p class="mr-3">Copyright © {% now "Y" %}</p>
  {% if not user.is_authenticated %}
    <p class="mr-3">
      <span class="mr-1">Ets d'una protectora?</span>
      <a href="{% url "core:login" %}" class="text-nowrap">Iniciar sessió</a>
    </p>
  {% endif %}
  <a href="{% url "sitemap" %}" target="_blank" class="mr-3">{% trans "Mapa del lloc" %}</a>
  <a href="{% url "core:about" %}#contacte">{% trans "Contacte" %}</a>
</div>

core/templates/core/layout.html
{% load i18n %}

{# Load the tag library #}
{% load bootstrap4 %}

{% bootstrap_javascript jquery='full' %}

{% load static %}

<!DOCTYPE html>
<html lang="ca">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content="Animals en adopció, gossets i gatets que necessiten una família i informació útil pels nostres amics peluts"/>
  <meta name="keywords" content="animal,animals,animal de companyia,adoptar,adopció,gat,gos,gatet,gosset,protectora"/>
  <meta name="robots" content="noindex, nofollow"/>

  <!-- generic -->
  <link rel="icon" href="{% static "favicon.png" %}" sizes="196x196"/>

  <!-- Android -->
  <link rel="shortcut icon" sizes="196x196" href="{% static "favicon.png" %}"/>

  <!-- iOS -->
  <link rel="apple-touch-icon" href="{% static "favicon.png" %}" sizes="192x192"/>

  <!-- Windows 8 IE 10-->
  <meta name="msapplication-TileColor" content="#FFFFFF"/>
  <meta name="msapplication-TileImage" content="{% static "favicon.png" %}"/>

  <!-- Windows 8.1 + IE11 and above -->
  <meta name="msapplication-config" content="{% static "browserconfig.xml" %}"/>

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Baloo&display=swap"/>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/flatly/bootstrap.min.css"/>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.1/css/all.css"/>

  <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}"/>

  <title>
    {% block title %}
      {% trans 'Amic Pelut' %}
    {% endblock %}
  </title>

  {% block head %}{% endblock %}

  {% if not settings.DEBUG %}
    {# On-premise Matomo analytics #}
    <script type="text/javascript">
      var _paq = window._paq || [];
      _paq.push(["setCookieDomain", "*.amicpelut.com"]);
      _paq.push(["setDomains", ["*.amicpelut.com"]]);
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function () {
        var u = "//data.amicpelut.com/";
        _paq.push(['setTrackerUrl', u + 'matomo.php']);
        _paq.push(['setSiteId', '1']);
        var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
        g.type = 'text/javascript';
        g.async = true;
        g.defer = true;
        g.src = u + 'matomo.js';
        s.parentNode.insertBefore(g, s);
      })();
    </script>
    {# End on-premise Matomo analytics #}
  {% endif %}
</head>
<body>
<div class="container d-flex flex-column" style="min-height: 100vh;">
  {% include 'core/navbar.html' %}
  {% bootstrap_messages %}
  <div class="flex-grow-1">
    {% block content %}{% endblock %}
  </div>
  {% include 'core/footer.html' %}
</div>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>
</body>
</html>

core/templates/core/navbar.html
{% load i18n %}
{% load static %}

<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-white">
  <a class="navbar-brand" href="{% url 'core:home' %}">
    <img src="{% static 'images/logo-title.png' %}" alt="{% trans 'Amic Pelut' %}" />
  </a>
  <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a href="{% url "adoptions:cats" %}" class="nav-link{% if section == 'cats' %} active{% endif %}">{% trans 'Gats' %}</a>
      </li>
      <li class="nav-item">
        <a href="{% url "adoptions:dogs" %}" class="nav-link{% if section == 'dogs' %} active{% endif %}">{% trans 'Gossos' %}</a>
      </li>
      <li class="nav-item">
        <a href="{% url "adoptions:adopted" %}" class="nav-link{% if section == 'adopted' %} active{% endif %}">
          {% trans "Adoptats" %}
        </a>
      </li>
      <li class="nav-item">
        <a href="{% url "organizations:organizations" %}" class="nav-link{% if section == 'organizations' %} active{% endif %}">
          {% trans 'Protectores' %}
        </a>
      </li>
      <li class="nav-item{% if section == 'about' %} active{% endif %}">
        <a href="{% url 'core:about' %}" class="nav-link">{% trans 'Sobre nosaltres' %}</a>
      </li>
    </ul>
    {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <li class="nav-item{% if section == 'dashboard' %} active{% endif %}">
          <a href="{% url 'core:dashboard' %}" class="nav-link">
            <i class="fa fa-cog"></i>
            {% trans 'Panell de Control' %}
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url "core:logout" %}" class="nav-link" data-toggle="tooltip" title="{% trans 'Tancar sessió' %}">
            <i class="fas fa-sign-out-alt"></i>
          </a>
        </li>
      </ul>
    {% endif %}
  </div>
</nav>